apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels: 
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule   #must be same name as app: in services file
  template:
    metadata:
      labels:
        app: train-schedule
    spec: 
      containers:
      - name: train-schedule
        image: 474721451157.dkr.ecr.us-east-1.amazonaws.com/train-schedule:latest   # get it from container image Details URI
        ports: 
        - containerPort: 30010  # must be same as containerport in service file


