apiVersion: v1
kind: Pod
metadata:
  name: train-schedule
  labels:
    app: train-schedule
spec:
  containers:
    - name: train-schedule
      image: tekstar/train-schedule:v1
      ports:
        - containerPort: 8080
