apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service
spec:
  type: NodePort
  selector: 
    app: train-schedule     # must be same as containerport in deployment file
  ports:
  -protocol: TCP
   port: 8080
   nodeport: 30010    # must be same as containerport in service file

